baseURL = 'https://gochi.netlify.app/'
languageCode = 'en-us'
title = 'Yuri Oliveira Gochi'
theme = "tale-hugo"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
