baseURL = 'https://gochi.netlify.app/'
languageCode = 'pt-br'
title = 'Gochi Dev'
theme = "tale-hugo"
DefaultContentLanguage = "pt-br"

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
